name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pickTeam:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
    - name: Setup Python
      uses: actions/setup-python@v5.2.0
    - name: Install glpk-utils
      run: sudo apt-get install glpk-utils
    - name: Install numpy
      run: pip3 install numpy
    - name: Install other deps
      run: pip3 install pandas pulp requests torch
    - name: Run solver
      env:
        FANTASY_PL_USERNAME: ${{ secrets.FANTASY_PL_USERNAME }}
        FANTASY_PL_PASSWORD: ${{ secrets.FANTASY_PL_PASSWORD }}
      run: python3 main.py $FANTASY_PL_USERNAME --password $FANTASY_PL_PASSWORD --log-level debug --apply --check-deadline
